Journal/urls.py
from django.urls import path

from django.conf.urls.static import static

from . import views, viewsrest
from JournalBase import settings

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.log_in, name='login'),

    path('journal/profile/<int:user_id>', views.profile, name='profile'),
    path('journal/profile/<int:user_id>/delete', views.user_delete, name='user_delete'),
    path('journal/profile/<int:user_id>/imagerotate', views.rotate_image, name='rotate_image'),

    path('journal/schedule/', views.schedule, name='schedule'),

    path('journal/schedule/<str:class_title>/<str:month_title>/<str:week_numbers>', views.class_schedule,
         name='class_schedule'),

    path('journal/classes/', views.classes, name='classes'),
    path('journal/classes/<int:class_id>/', views.thisclass, name='thisclass'),
    path('journal/classes/<int:class_id>/delete/', views.class_delete, name='class_delete'),

    path('journal/users/', views.users, name='users'),

    path('journal/lessons/', views.lessons, name='lessons'),

    path('journal/homework', views.homework, name='homework'),
    path(
        'journal/homework/assign/<int:ih_id>/<int:submithomework_id>/<int:homework_id>/<int:schoolclass_id>/'
        '<int:student_id>',
        views.assign_grade, name='assign_grade'),

    path('journal/homework/submit/<int:homework_id>', views.submit_homework, name='submit_homework'),

    path('journal/homework/check/<int:homework_id>', views.check_homework, name='check_homework'),

    path('journal/download/<int:ih_id>/<int:sh_id>', views.download, name='download'),

    path('journal/homework/individual/<int:schoolclass_id>/<int:student_id>', views.individual_homework,
         name='individual_homework'),
    path('journal/homework/individual/submit/<int:individualhomework_id>', views.submit_individualhomework,
         name='submit_individualhomework'),

    path('journal/grades/', views.grades, name='grades'),

    path('journal/homework/close/<int:h_id>', views.close_homework, name='close_homework'),
    path('journal/homework/individual/close/<int:h_id>', views.close_individualhomework,
         name='close_individualhomework'),

    path('logout/', views.logout_view, name='logout'),

    path('api/', views.api, name='api'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

JournalBase/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
    path('admin/', admin.site.urls),

    path('', include('Journal.urls')),

    path('api/v1/', include('Journal.urlsrest')),
]

Journal/models.py
from django.db import models
from django.contrib.auth.models import User

import os


class Grade(models.Model):
    grade = models.CharField(max_length=3)
    color = models.CharField(max_length=7, null=True)


class UserImage(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/', null=True, blank=True)


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return '{} {}'.format(self.user.first_name, self.user.last_name)


class SchoolClass(models.Model):
    title = models.CharField(max_length=3, default="", unique=True)
    students = models.ManyToManyField(User, blank=True)

    def __str__(self):
        return '%s' % self.title.capitalize()


class Lesson(models.Model):
    title = models.CharField(max_length=50, default="", unique=True)

    def __str__(self):
        return '%s' % self.title


class Day(models.Model):
    title = models.CharField(max_length=10, default="", unique=True)

    def __str__(self):
        return '%s' % self.title


class Schedule(models.Model):
    day = models.ForeignKey(Day, on_delete=models.CASCADE, default="")
    schoolclass = models.ForeignKey(SchoolClass, on_delete=models.CASCADE, default="")
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, default="")

    lessonteacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default="", blank=True, null=True)

    date = models.DateField(blank=True, null=True)

    start = models.TimeField(blank=True, null=True)
    end = models.TimeField(blank=True, null=True)

    def __str__(self):
        return 'Schoolclass: {}, Lesson: {}'.format(self.schoolclass, self.lesson)


class HomeWork(models.Model):
    schedule = models.ForeignKey(Schedule, on_delete=models.CASCADE, default="", null=True)

    text = models.TextField(default="")

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default="")

    isWithFile = models.BooleanField(default=False)

    def get_teacher(self):
        return self.schedule.lessonteacher


class SubmitHomework(models.Model):
    homework = models.ForeignKey(HomeWork, on_delete=models.CASCADE)
    file = models.FileField(upload_to='files/', null=True, blank=True)
    student = models.ForeignKey(User, on_delete=models.CASCADE, default="")

    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, default="", null=True)
    comment = models.TextField(default="", null=True)

    def get_filename(self):
        path = self.file.path
        base = os.path.basename(path)

        return base


class IndividualHomework(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, default="", null=True)
    text = models.TextField(default="")

    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE, default="")

    isWithFile = models.BooleanField(default=False)
    file = models.FileField(upload_to='files/', null=True, blank=True)

    grade = models.ForeignKey(Grade, on_delete=models.CASCADE, default="", null=True)
    comment = models.TextField(default="", null=False)

    def get_filename(self):
        path = self.file.path
        base = os.path.basename(path)

        return base

Journal/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import check_password
from django.contrib.auth.models import User

from .urlsrest import urlpatterns

from PIL import Image

import re
from django.utils.translation import ugettext as _

from .functions import get_data

from .forms import AuthForms, ClassAddForms, ScheduleAddForms, UserAddForms, HomeWorkForms, LessonAddForms, \
    UserImageForm, UserEditForms, ClassStudentsAddForms, GradesForms, IndividualHomeWorkForms
from .models import Day, SchoolClass, Lesson, Schedule, HomeWork, UserImage, Teacher, IndividualHomework, \
    SubmitHomework, Grade

from rest_framework.authtoken.models import Token

classes = SchoolClass.objects.all()

titles = [classes_.title for classes_ in classes]


def key(s):
    num, letters = re.match(r'(\d*)(.*)', s).groups()
    return float(num or 'inf'), letters


sorted_titles = sorted(titles, key=key)

weeks = {'1-7': [1, 2, 3, 4, 5, 6, 7], '8-14': [8, 9, 10, 11, 12, 13, 14], '15-21': [15, 16, 17, 18, 19, 20, 21],
         '22-28': [22, 23, 24, 25, 26, 27, 28], '29-31': [29, 30, 31]}


def index(request):  # Getting started
    if request.user.is_authenticated:
        return redirect('homework')

    return render(request, 'Journal/index.html')


def log_in(request):
    if request.method == 'GET':
        forms = AuthForms()
        return render(request, 'Journal/login.html', {'forms': forms})
    else:
        forms = AuthForms(request.POST)
        if forms.is_valid():
            username = forms.cleaned_data['username']
            password = forms.cleaned_data['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('schedule')
            else:
                msg = _('The entered data is incorrect')
                return render(request, 'Journal/login.html', {'forms': forms, 'msg': msg})
        else:
            msg = _('The entered data is incorrect')
            return render(request, 'Journal/login.html', {'forms': forms, 'msg': msg})


@login_required(login_url="/login/")
def schedule(request):
    if request.method == 'GET':
        if request.user.groups.values_list('name', flat=True).first() == 'Admin':
            return render(request, 'Journal/schedule.html', {'titles': sorted_titles})
        else:
            return redirect('index')


@login_required(login_url="/login/")
def class_schedule(request, class_title, month_title, week_numbers):
    if request.method == 'POST':
        form = ScheduleAddForms(request.POST)

        if form.is_valid():
            day = form.cleaned_data['day']  # object

            schoolclass = SchoolClass.objects.filter(title=class_title).first()

            lesson = form.cleaned_data['lesson']
            lessonteacher = form.cleaned_data['lessonteacher']

            date = request.POST['date']  # str: YYYY-MM-DD

            start = request.POST['start']  # str: HH:MM
            end = request.POST['end']

            new_schedule = Schedule(day=day, schoolclass=schoolclass, lesson=lesson, lessonteacher=lessonteacher,
                                    date=date,
                                    start=start, end=end)
            new_schedule.save()

            return redirect('class_schedule', class_title, 'September', '1-7')

    else:
        if request.user.groups.get().name == 'Student' and request.user.schoolclass_set.first().title != class_title:
            return redirect('class_schedule', request.user.schoolclass_set.first().title, 'September', '1-7')

        schoolclass = SchoolClass.objects.filter(title=class_title).first()
        all_schedules = Schedule.objects.filter(schoolclass=schoolclass).all().order_by('start')

        days_choose = {_('Monday'): 'Monday', _('Tuesday'): 'Tuesday', _('Wednesday'): 'Wednesday',
                       _('Thursday'): 'Thursday', _('Friday'): 'Friday', _('Saturday'): 'Saturday',
                       _('Sunday'): 'Sunday', }

        days = Day.objects.all()

        alllessons = Lesson.objects.all()

        months_choose = {_('January'): 'January', _('February'): 'February', _('March'): 'March', _('April'): 'April',
                         _('May'): 'May', _('June'): 'June', _('Jule'): 'Jule', _('August'): 'August',
                         _('September'): 'September',
                         _('October'): 'October', _('November'): 'November', _('December'): 'December', }

        months = {'January': 1, 'February': 2, 'March': 3, 'April': 4, 'May': 5, 'June': 6, 'Jule': 7, 'August': 8,
                  'September': 9, 'October': 10, 'November': 11, 'December': 12}

        schedules = []
        for i in all_schedules:
            date_datetime = i.date

            day = int(date_datetime.strftime('%d'))
            month = int(date_datetime.strftime('%m'))

            if month == months[month_title] and day in weeks[week_numbers]:
                schedules.append(i)

        schedules_monday = [s for s in schedules if s.day.title == 'Monday']
        schedules_tuesday = [s for s in schedules if s.day.title == 'Tuesday']
        schedules_wednesday = [s for s in schedules if s.day.title == 'Wednesday']
        schedules_thursday = [s for s in schedules if s.day.title == 'Thursday']
        schedules_friday = [s for s in schedules if s.day.title == 'Friday']

        schedules_days = list()
        schedules_days.append(schedules_monday)
        schedules_days.append(schedules_tuesday)
        schedules_days.append(schedules_wednesday)
        schedules_days.append(schedules_thursday)
        schedules_days.append(schedules_friday)

        form = ScheduleAddForms()

        return render(request, 'Journal/schedule.html', {'titles': sorted_titles,
                                                         'class_title': class_title,
                                                         'all_schedules': all_schedules,
                                                         'days_choose': days_choose,
                                                         'days': days,
                                                         'lessons': alllessons,
                                                         'schedules_days': schedules_days,
                                                         'months_choose': months_choose,
                                                         'months': months,
                                                         'month_title': month_title,
                                                         'weeks': weeks,
                                                         'week_numbers': week_numbers,

                                                         'form': form,
                                                         })


@login_required(login_url="/login/")
def classes(request):
    schoolclasses = SchoolClass.objects.all()
    addforms = ClassAddForms()
    if request.user.groups.values_list('name', flat=True).first() != 'Admin':
        return redirect('index')
    elif request.method == 'GET':

        return render(request, 'Journal/classes.html', {'titles': sorted_titles,
                                                        'schoolclasses': schoolclasses, 'addforms': addforms})
    else:
        form = ClassAddForms(request.POST)
        if form.is_valid():
            title = form.cleaned_data['title']

            new_class = SchoolClass(title=title)
            new_class.save()

            success = True
            return render(request, 'Journal/classes.html', {'titles': sorted_titles,
                                                            'schoolclasses': schoolclasses, 'addforms': addforms,
                                                            'success': success})

        error = True
        return render(request, 'Journal/classes.html', {'titles': sorted_titles,
                                                        'schoolclasses': schoolclasses, 'addforms': addforms,
                                                        'error': error})


@login_required(login_url='/login')
def thisclass(request, class_id):
    curr_class = SchoolClass.objects.filter(id=class_id).first()

    if request.method == 'GET':
        forms = ClassStudentsAddForms()
        curr_class_students = curr_class.students.all()

        return render(request, 'Journal/thisclass.html', {'forms': forms, 'curr_class': curr_class,
                                                          'students': curr_class_students})

    else:
        forms = ClassStudentsAddForms(request.POST)
        if forms.is_valid():
            students_id = forms.data.getlist('students')

            for student_id in students_id:
                curr_class.students.add(student_id)

            curr_class.save()

            return redirect('thisclass', curr_class.id)


@login_required(login_url="/login/")
def class_delete(request, class_id):
    if request.user.groups.values_list('name', flat=True).first() != 'Admin':
        return redirect('index')
    c = SchoolClass.objects.filter(id=class_id).first()
    c.delete()

    return redirect('classes')


@login_required(login_url="/login/")
def users(request):
    allusers = User.objects.all()

    forms = UserAddForms()
    image_form = UserImageForm()

    if request.user.groups.values_list('name', flat=True).first() != 'Admin':
        return redirect('index')
    elif request.method == 'GET':
        return render(request, 'Journal/users.html', {'users': allusers, 'forms': forms, 'image_form': image_form})
    else:
        forms_post = UserAddForms(request.POST)
        image_form = UserImageForm(request.POST, request.FILES)
        if forms_post.is_valid() and image_form.is_valid():

Journal/templates/Journal/api.html
{% extends 'Journal/base.html' %}

{% load i18n %}

{% block title %}
    {% trans 'Electronic school journal' %} API
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">
            <h3 class="display-3">{% trans 'Electronic school journal' %} API</h3>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            {% if token %}
                {% trans 'Your token' %}: {{ token.key }}
            {% else %}
                {% trans 'You currently do not have a token' %}
            {% endif %}
            <br/><br/>

            <div class="row">

                <form action="{% url 'api' %}" method="post">
                    {% if not token %}

                        <div class="col-sm">
                            <button type="submit" class="btn btn-primary">

                                {% trans 'Generate token' %}

                            </button>
                        </div>

                    {% endif %}

                    {% if token %}
                        <div class="col-sm">
                            <button type="submit" class="btn btn-warning">
                                {% trans 'Destroy my token' %}
                            </button>
                        </div>

                    {% endif %}

                </form>
            </div>

        </div>
    </div>

    {% if urlpatterns %}

        <div class="card">
            <div class="card-body">

                {% for u in urlpatterns %}
                    {{ u }}
                    <br />
                {% endfor %}

            </div>
        </div>

    {% endif %}


{% endblock %}

Journal/templates/Journal/check_homework.html
{% extends 'Journal/base.html' %}

{% load i18n %}

{% block title %}
    {% trans 'Checking homework' %}
{% endblock %}

{% block body %}

    <div class="card">
        <div class="card-body">
            <h4 class="display-4">{% trans 'Homework' %} #{{ thishomework.id }}</h4>

            {{ thishomework.text }}<br/>
            {% trans 'For' %} {{ thishomework.schedule.schoolclass.title }} {% trans 'class' %}
        </div>
    </div>

    <div class="card">
        <div class="card-body">

            <div class="row">
                {% for submithomework in thishomework.submithomework_set.all %}
                    {% if not submithomework.grade %}
                        <div class="col-sm-3">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ submithomework.student.first_name }} {{ submithomework.student.last_name }}</h5>
                                    <p class="card-text"><a
                                            href="{% url 'download' 0 submithomework.id %}">{{ submithomework.get_filename }}</a>
                                    </p>

                                    {% if request.user.groups.get.name != 'Admin' %}
                                        <form action="{% url 'assign_grade' 0 submithomework.id thishomework.id 0 0 %}"
                                              method="post">

                                            <label for="comment">Comment:</label>
                                            <textarea required id="comment" name="comment"></textarea><br/>

                                            <label for="choosegrade">Grade:</label>
                                            <select id="choosegrade" name="choosegrade" class="form-control">
                                                {% for grade in grades %}
                                                    <option style="color: {{ grade.color }}"
                                                            value="{{ grade.id }}">{{ grade.grade }}</option>
                                                {% endfor %}
                                            </select>
                                            <br/>

                                            <button type="submit" class="btn btn-outline-dark">
                                                Send
                                            </button>

                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endif %}

                {% endfor %}
            </div>

        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                {% for submithomework in thishomework.submithomework_set.all %}
                    {% if submithomework.grade %}
                        <div class="col-sm-3">
                            <div class="card" style="width: 18rem;">
                                <div class="card-body">
                                    <h5 class="card-title">{{ submithomework.student.first_name }} {{ submithomework.student.last_name }}</h5>
                                    <p class="card-text"><a
                                            href="{% url 'download' 0 submithomework.id %}">{{ submithomework.get_filename }}</a>
                                    </p>

                                    {{ submithomework.comment }}
                                    <br/><br/>
                                    <h3 style="color: {{ submithomework.grade.color }}">{{ submithomework.grade.grade }}</h3>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

Journal/templates/Journal/homework.html
{% extends 'Journal/base.html' %}

{% load i18n %}

{% block title %}
    {% trans 'Class homework' %}
{% endblock %}

{% load crispy_forms_filters %}

{% block body %}
    <div class="card">
        <div class="card-body">
            <h3 class="display-3">{% trans 'Class homework' %}</h3>
        </div>
    </div>
    {% if request.user.groups.get.name == 'Teacher' %}

        <div class="card">
            <div class="card-body">


                {% if error %}
                    <div class="col-md">
                        <div class="alert alert-danger" role="alert">
                            {% trans 'There was an error adding a new homework' %}
                        </div>
                    </div>
                {% endif %}

                {% if success %}
                    <div class="col-md">
                        <div class="alert alert-success" role="alert">
                            {% trans 'New homework added successfully' %}
                        </div>
                    </div>
                {% endif %}

                <div class="accordion" id="accordion">
                    <div class="card">
                        <div class="card-header" id="headingTwo">
                            <h5 class="mb-0">
                                <button class="btn btn-link" data-toggle="collapse" data-target="#collapseTwo"
                                        aria-controls="collapseTwo">
                                    {% trans 'Homework assignment' %}
                                </button>
                            </h5>
                        </div>

                        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
                            <div class="card-body">

                                <form action="{% url 'homework' %}"
                                      method="post">


                                    <div class="form-row">
                                        <div class="form-group col-md-2 mb-0">
                                            {{ forms.schedule|as_crispy_field }}
                                        </div>
                                    </div>

                                    <br/>
                                    <div class="form-row">
                                        {{ forms.text|as_crispy_field }}
                                    </div>

                                    <div class="form-row">
                                        {{ forms.isWithFile|as_crispy_field }}
                                    </div>


                                    <br/>
                                    <button type="submit" class="btn btn-outline-dark col-md-1">
                                        {% trans 'Add' %}
                                    </button>
                                </form>

                            </div>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    {% endif %}




    <div class="card">
        <div class="card-body">

            {% if request.user.groups.get.name == 'Teacher' or request.user.groups.get.name == 'Admin' %}

                <div class="row">
                    {% for h in homeworks %}

                        <div class="col-sm">
                            <div class="card" style="width: 18rem;">

                                <div class="card-header">
                                    <ul class="nav nav-tabs card-header-tabs">
                                        <li class="nav-item">
                                            <a class="nav-link active"
                                               href="{% url 'close_homework' h.id %}">{% trans 'Close' %}</a>
                                        </li>
                                    </ul>
                                </div>

                                <div class="card-body">

                                    <h5 class="card-title">Homework for
                                        "{{ h.schedule.schoolclass.title }}" - {{ h.schedule.lesson }}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        {{ h.text }}
                                    </h6>

                                    {% if request.user.groups.get.name == 'Admin' %}
                                        {% trans 'Teacher' %} -
                                        <a href="{% url 'profile' h.teacher.user.id %}"
                                           class="card-link">{{ h.teacher.user.first_name }} {{ h.teacher.user.last_name }}</a>
                                    {% endif %}
                                </div>

                                {% if h.isWithFile %}
                                    <div class="card-header">
                                        {% if h.submithomework_set.all|length == 0 %}
                                            {% trans 'No one has sent homework yet' %}

                                        {% elif h.submithomework_set.all|length == 1 %}
                                            1 {% trans 'work' %}
                                            <a href="{% url 'check_homework' h.id %}"
                                               class="btn btn-link"
                                               style="margin-left:15px">--></a>

                                        {% else %}
                                            {{ h.submithomework_set.all|length }} {% trans 'works' %}
                                            <a href="{% url 'check_homework' h.id %}"
                                               class="btn btn-link"
                                               style="margin-left:15px">--></a>
                                        {% endif %}


                                    </div>
                                {% endif %}
                            </div>
                        </div>

                    {% endfor %}
                </div>


            {% endif %}


            {% if request.user.groups.get.name == 'Student' %}

                <div class="row">
                    {% for homework in homeworks %}

                        <div class="col-sm">
                            <div class="card" style="width: 26rem">
                                <div class="card-body">
                                    <h5 class="card-title">{% trans 'Homework for' %} "{{ homework.schedule.schoolclass.title }}"
                                        - {{ homework.schedule.lesson }}</h5>
                                    <h6 class="card-subtitle mb-2 text-muted">
                                        {{ homework.text }}
                                    </h6>

                                    {#                        <a href="{% url 'profile' homework.get_teacher.user.id %}">{{ homework.get_teacher.first_name }}#}
                                    {#                            {{ homework.get_teacher.last_name }}</a>#}

                                    <a href="#" class="card-link"></a>

                                    {% for submitted_homework in homework.submithomework_set.all %}
                                        {% if submitted_homework.student == request.user %}
                                            {% if submitted_homework.grade %}
                                                <h3 style="color: {{ submitted_homework.grade.color }}">{{ submitted_homework.grade.grade }}</h3>
                                                <br/>
                                                {{ submitted_homework.comment }}
                                            {% endif %}
                                        {% endif %}
                                    {% endfor %}

                                </div>

                                {% if homework.isWithFile is True %}
                                    <div class="card-header">
                                        {% if request.user.groups.get.name != 'Admin' %}
                                            {% if homework not in submitted_homeworks %}
                                                <form enctype="multipart/form-data"
                                                      action="{% url 'submit_homework' homework.id %}"
                                                      method="post">
                                                    {% csrf_token %}

                                                    <input type="file" name="homework_file" required>


                                                    <button class="btn btn-secondary" type="submit">{% trans 'Submit' %}</button>
                                                </form>
                                            {% else %}
                                                {% for submitted_homework in homework.submithomework_set.all %}
                                                    {% if submitted_homework.student == request.user %}
                                                        <a href="{% url 'download' 0 submitted_homework.id %}">{{ submitted_homework.get_filename }}</a>
                                                    {% endif %}
                                                {% endfor %}

                                            {% endif %}

                                        {% else %}
                                            {% trans 'With file submit' %}

                                        {% endif %}

                                    </div>
                                {% endif %}

                            </div>
                        </div>

                    {% endfor %}
                </div>

            {% endif %}
        </div>
    </div>
{% endblock %}